name = "Chat-Doc"
version = "0.0.1"
description = "QLoRA-based fine-tuning of llama-2 for a medical-diagnosis/doctor chat-bot"
license = "MIT"
authors = [
    "Tilman Kerl <tilmankerl@pm.me>",
]
repository = "https://github.com/MisterXY89/chat-doc/"

[tool.black]
line-length = 100
include = '\.pyi?$'
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | .env
  | _build
  | buck-out
  | build
  | dist
  | env
)/
'''

[tool.isort]
profile = "black"
