api:
  token: 
  mail: who.gfnlq@passmail.net
  max_retries: 3
  client_id: 11754030-fc21-4204-88cd-89e8c2a48f9a_12d03ab9-9b1d-4d3b-a262-13dba7a9c3ca
  client_secret: 3ZHiukddMxC1Cr3KvRhihQonwNYZrUg993kpNvW4aao=