app: 
  name: "Chat-Doc"
  description: "Chat-Doc is a chat application for medical diagnosis."
  version: "0.0.1"
auth:
  hf_token: "YOUR_HF_TOKEN"  
logging:
  version: 1
  formatters:
    simple:
      format: '[%(asctime)s] - %(levelname)s : %(message)s'
      datefmt: '%d/%m/%Y %H:%M:%S'
  handlers:
    console:
      class: logging.StreamHandler
      level: DEBUG
      formatter: simple
      stream: ext://sys.stdout
  loggers:
    sampleLogger:
      level: INFO
      handlers: [console]
      propagate: no
  root:
    level: INFO
    handlers: [console]

