name: Python Package Using Anaconda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        $CONDA/bin/conda env update --file environment.yml --name adl

    - name: Lint with flake8
      run: |
        $CONDA/bin/conda install flake8
        # Lint using flake8 with settings from .flake8 file
        $CONDA/bin/flake8 --config .flake8

    - name: Test with pytest
      run: |
        $CONDA/bin/conda install pytest
        $CONDA/bin/pytest
