name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        miniconda-version: "latest"
        python-version: "3.10"
        activate-environment: adl
        environment-file: environment.yml
        condarc-file: condarc.yml

    # Assuming you have an environment.yml that specifies dependencies.
    # If not, you can use conda or mamba commands to install packages directly
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name adl

    - name: Lint with flake8
      run: |
        conda run --name adl flake8 --config .flake8

    - name: Test with pytest
      run: |
        conda run --name adl python -m pytest
