name: ChatDoc CI

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name adl
        echo "source activate $(head -1 environment.yml | cut -d' ' -f2)" >> $BASH_ENV
        source $BASH_ENV

    - name: Lint with flake8
      run: |
        conda install flake8
        # Lint using flake8 with settings from .flake8 file
        flake8 --config .flake8

    - name: Test with pytest
      run: |
        conda install pytest
        pytest

env:
  CACHE_NUMBER: 0  #